In [4]:
# Importing necessary libraries
import pandas as pd
import numpy as np

# Load the dataset from the desktop (adjust the file name if necessary)
file_path = '/Users/audrey/Desktop/Employee_Turnover_Dataset.xlsx'  # Modify the path if needed
df = pd.read_excel(file_path)

# A.1.a Describe the general characteristics of the initial dataset (e.g., rows, columns)
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print(df.columns)

# A.1.b Indicate the data type and data subtype for each variable
print(df.dtypes)

# A.1.c Provide a sample of observable values for each variable
print(df.sample(5))

# Check for missing values
print("\nMissing Values:\n", df.isnull().sum())

# B.1 Inspect for duplicate entries
duplicates = df.duplicated()
print(f"Number of duplicate rows: {duplicates.sum()}")

# B.1 Inspect for missing values
missing_values = df.isnull().sum()
print("Missing values per column:\n", missing_values)

# B.1 Check for outliers (Using IQR for numeric data)
numeric_cols = df.select_dtypes(include=np.number).columns
Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

outliers = ((df[numeric_cols] < (Q1 - 1.5 * IQR)) | (df[numeric_cols] > (Q3 + 1.5 * IQR))).sum()
print("\nOutliers per column:\n", outliers)

# B.2 List findings for each quality issue
print("Findings:\n")
print(f"Columns with missing values:\n{missing_values[missing_values > 0]}")
print(f"Columns with outliers:\n{outliers[outliers > 0]}")
print(f"Number of duplicate rows: {duplicates.sum()}")

# C.1 Removing duplicates
df_cleaned = df.drop_duplicates()

# C.2 Handling missing values (replace missing values with median for numeric columns)
for col in numeric_cols:
    if df_cleaned[col].isnull().sum() > 0:
        df_cleaned[col] = df_cleaned[col].fillna(df_cleaned[col].median())

# C.2 Handling missing values for categorical columns (replace missing values with mode)
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    if df_cleaned[col].isnull().sum() > 0:
        df_cleaned[col] = df_cleaned[col].fillna(df_cleaned[col].mode()[0])

# C.3 Handling outliers (cap outliers using the IQR method)
for col in numeric_cols:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
    df_cleaned.loc[df_cleaned[col] > upper_bound, col] = upper_bound

# C.3 Save the cleaned dataset
cleaned_file_path = '/Users/audrey/Desktop/Employee_Turnover_Cleaned.csv'
df_cleaned.to_csv(cleaned_file_path, index=False)

# Display cleaned dataset summary
print(f"Cleaned Dataset: {df_cleaned.shape}")
print(f"Head of Cleaned Data:\n{df_cleaned.head()}")

Number of rows: 10322
Number of columns: 35
Index(['Age', 'Turnover', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')
Age                         float64
Turnover                     object
BusinessTravel               object
DailyRate                     int64
Department                   object
DistanceFromHome              int64
Education                     int64
EducationField               object
EmployeeCount                 int64
EmployeeNumber                int64
EnvironmentSatisfaction       int64
Gender                       object
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                      object
JobSatisfaction               int64
MaritalStatus                object
MonthlyIncome               float64
MonthlyRate                 float64
NumCompaniesWorked          float64
Over18                       object
OverTime                     object
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
StandardHours                 int64
StockOptionLevel              int64
TotalWorkingYears           float64
TrainingTimesLastYear       float64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion     float64
YearsWithCurrManager         object
dtype: object
       Age Turnover     BusinessTravel  DailyRate Department  \
1988  19.0      Yes      Travel_Rarely        423   Hardware
4269  21.0      Yes      Travel_Rarely        865   Hardware
3161  19.0      Yes  Travel_Frequently       1254    Support
9567  48.0       No         Non-Travel        167   Hardware
5047  47.0       No  Travel_Frequently        210    Support

      DistanceFromHome  Education EducationField  EmployeeCount  \
1988                49          4      Marketing              1
4269                24          1  Life Sciences              1
3161                23          1        Medical              1
9567                34          1  Life Sciences              1
5047                15          3  Life Sciences              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
1988            4872  ...                         2            80
4269            4180  ...                         3            80
3161            2392  ...                         4            80
9567            8292  ...                         1            80
5047             485  ...                         2            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
1988                 4                9.0                    6.0
4269                 4               29.0                    5.0
3161                 3               17.0                    2.0
9567                 2               37.0                    4.0
5047                 4               25.0                    4.0

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
1988               1               3                  2
4269               4              14                 10
3161               3              16                  2
9567               4              16                  2
5047               1              25                 17

      YearsSinceLastPromotion  YearsWithCurrManager
1988                      2.0                     1
4269                      3.0                     2
3161                      3.0                    12
9567                      5.0                    12
5047                     19.0                    24

[5 rows x 35 columns]

Missing Values:
 Age                           1
Turnover                      0
BusinessTravel                0
DailyRate                     0
Department                    0
DistanceFromHome              0
Education                     0
EducationField                2
EmployeeCount                 0
EmployeeNumber                0
EnvironmentSatisfaction       0
Gender                        3
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobRole                       0
JobSatisfaction               0
MaritalStatus                 0
MonthlyIncome                 1
MonthlyRate                   2
NumCompaniesWorked            1
Over18                        0
OverTime                      0
PercentSalaryHike             0
PerformanceRating             0
RelationshipSatisfaction      0
StandardHours                 0
StockOptionLevel              0
TotalWorkingYears             1
TrainingTimesLastYear       418
WorkLifeBalance               0
YearsAtCompany                0
YearsInCurrentRole            0
YearsSinceLastPromotion       2
YearsWithCurrManager          0
dtype: int64
Number of duplicate rows: 298
Missing values per column:
 Age                           1
Turnover                      0
BusinessTravel                0
DailyRate                     0
Department                    0
DistanceFromHome              0
Education                     0
EducationField                2
EmployeeCount                 0
EmployeeNumber                0
EnvironmentSatisfaction       0
Gender                        3
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobRole                       0
JobSatisfaction               0
MaritalStatus                 0
MonthlyIncome                 1
MonthlyRate                   2
NumCompaniesWorked            1
Over18                        0
OverTime                      0
PercentSalaryHike             0
PerformanceRating             0
RelationshipSatisfaction      0
StandardHours                 0
StockOptionLevel              0
TotalWorkingYears             1
TrainingTimesLastYear       418
WorkLifeBalance               0
YearsAtCompany                0
YearsInCurrentRole            0
YearsSinceLastPromotion       2
YearsWithCurrManager          0
dtype: int64

Outliers per column:
 Age                           2
DailyRate                     0
DistanceFromHome              3
Education                     0
EmployeeCount                 3
EmployeeNumber                0
EnvironmentSatisfaction       0
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobSatisfaction               0
MonthlyIncome                 1
MonthlyRate                 147
NumCompaniesWorked            0
PercentSalaryHike             0
PerformanceRating             0
RelationshipSatisfaction      0
StandardHours                 0
StockOptionLevel              0
TotalWorkingYears             1
TrainingTimesLastYear         0
WorkLifeBalance               0
YearsAtCompany               84
YearsInCurrentRole          504
YearsSinceLastPromotion     550
dtype: int64
Findings:

Columns with missing values:
Age                          1
EducationField               2
Gender                       3
MonthlyIncome                1
MonthlyRate                  2
NumCompaniesWorked           1
TotalWorkingYears            1
TrainingTimesLastYear      418
YearsSinceLastPromotion      2
dtype: int64
Columns with outliers:
Age                          2
DistanceFromHome             3
EmployeeCount                3
MonthlyIncome                1
MonthlyRate                147
TotalWorkingYears            1
YearsAtCompany              84
YearsInCurrentRole         504
YearsSinceLastPromotion    550
dtype: int64
Number of duplicate rows: 298
Cleaned Dataset: (10024, 35)
Head of Cleaned Data:
    Age Turnover     BusinessTravel  DailyRate Department  DistanceFromHome  \
0  33.0      Yes         Non-Travel      241.0   Hardware              16.0
1  35.0      Yes         Non-Travel      679.0    Support               7.0
2  27.0      Yes  Travel_Frequently      359.0   Hardware              50.0
3  44.0       No      Travel_Rarely     1133.0   Software              12.0
4  56.0       No      Travel_Rarely      118.0   Software              43.0

   Education    EducationField  EmployeeCount  EmployeeNumber  ...  \
0          3  Technical Degree              1          3505.0  ...
1          2     Life Sciences              1          1129.0  ...
2          1     Life Sciences              1          6305.0  ...
3          5     Life Sciences              1          4595.0  ...
4          2   Human Resources              1          7203.0  ...

   RelationshipSatisfaction StandardHours  StockOptionLevel  \
0                       1.0            80                 4
1                       1.0            80                 1
2                       4.0            80                 4
3                       4.0            80                 3
4                       2.0            80                 1

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0               35.0                    4.0               4            13.0
1                5.0                    1.0               1             4.0
2               10.0                    4.0               2             4.0
3               19.0                    4.0               1            14.0
4                3.0                    3.0               4             1.0

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
0                2.0                      8.0                    11
1                3.0                      3.0                     4
2                2.0                      4.0                     2
3                7.0                     12.0                     2
4                1.0                      1.0                     1

[5 rows x 35 columns]

/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[col] = df_cleaned[col].fillna(df_cleaned[col].median())
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[col] = df_cleaned[col].fillna(df_cleaned[col].mode()[0])
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-602.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-24.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-5002.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-25.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-0.125' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-16.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound
/var/folders/yz/hpxxcq5s16gcl3n4cbkdb6ph0000gn/T/ipykernel_43048/3749798144.py:67: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-9.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cleaned.loc[df_cleaned[col] < lower_bound, col] = lower_bound